Last changes on index.html, styles.css and README.md file
migcm06/miguel-portfolio pull request #2
Opened 2023-04-28 21:01 UTC by migcm06

I have created a new branch for the last changes required of me in the last code review.

I changed some lines in the index.html and styles.css files (I changed by mistake the color from a decoration shape).

I uploaded the README.md.

2023-04-28 22:05 UTC, franclobo requested changes
Hi @migcm06, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/235261871-8f498efc-469d-429d-a475-4eb45f37bd45.gif)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- Professional README file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 22:05 UTC, franclobo commented on index.html
> +        <div id="circle1"></div>
- [ ] All the background images should be inserted like a CSS property. Please 🙏🏽 add the image in the correct way `background-image:` for the best practices of HTML & CSS.

2023-04-28 22:05 UTC, franclobo commented on index.html
- [ ] The LET'S CONNECT is a link, so please 🙏🏽 use the anchor tag `a` instead of the `hx` tag for the best practices of HTML & CSS.
- [ ] Kindly use the `ul` tag and the `li` to list all the social media icons and add a dot at the beginning of the path to avoid broken links 👇🏽 
- [ ] Please 🙏🏽 use flexbox for both sections header and section, add the spaces between the title, paragraph and link, and add the border-radius in the left corner to be similar to the Figma design.

| Code | Result | Figma design |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/235259917-226d9a10-00c9-4c17-8a68-516f17395c2b.png) | ![image](https://user-images.githubusercontent.com/58642949/235259977-7d23f724-19e9-4dc4-bc4b-eaaa9fb357b5.png) | ![image](https://user-images.githubusercontent.com/58642949/235261616-1f052f40-c826-4574-b17e-5db2ea26ac53.png) |

2023-04-28 22:05 UTC, franclobo commented on styles.css
> +@media (width <= 375px) {
- [ ] We are going to use media queries on the next block for the desktop version, please remove this until we need it.

2023-04-28 22:05 UTC, franclobo commented on styles.css
> +}
- [ ] Please 🙏🏽 use a background-image instead of importing the images one by one for the better practices of HTLM & CSS.

2023-04-29 01:06 UTC, migcm06 commented on index.html
Hello, thanks, I didn't see before that radius.

2023-04-29 19:31 UTC, merged